---
title: "R and RStudio installation"
author: "Sanghoon Lee"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  xaringan::moon_reader:
    css: [default, c407_slides.css]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## OS update

At home, update the OS on your computer to the latest version. Otherwise you may encounter mysterious errors your classmates do not have.

---

## R

Google 'Download R', choose 'https://www.r-project.org', and follow the 'CRAN' links to download R for your OS.

Please upgrade (i.e., remove and reinstall) R if you have an older version.

---

## RStudio

Google 'Download RStudio', and follow the links.

Choose 'RStudio Desktop - Open Source License'.

Please upgrade (i.e., remove and reinstall) RStudio if you have an older version.

---

## RStudio Set up

Tools - Global Options - General: Choose 'never' for Save workspace to .RData on exiting.

Tools - Global Options - General: Uncheck restore .RData into workspace at start up.

<!-- Tools - Global Options - Code - Saving: Choose 'UTF-8' for default text encoding. -->

<!-- View - Panes - Console on Right -->

Otherwise, your R sessions will become slow over time.

---


## Class Folder with Data

Download 'C407.zip' from Canvas - Files menu.

*Extract* it onto any folder on your computer.

---

How many data (rds) files does Data folder have?

A. 1

B. 2

C. 3

D. 4

E. 5

---

What is the name of the file in C407 folder? Do not include the ones in subfolders.

--

C407.Rproj is the project file for this folder. 

A project file sets the working folder to its location. 

Always begin by opening the project file in RStudio when you follow examples in this course.

