---
title: "ggplot2 - 3"
subtitle: "Geometries"
author: "Sanghoon Lee"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  answers: TRUE
output:
  xaringan::moon_reader:
    css: [default, c407_slides.css]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, comment=NA, fig.asp = 0.56, out.width='70%', dpi = 300, fig.align = 'center')
options(tibble.print_max = Inf)
library(kableExtra)
```

### Barchart

```{r}
library(tidyverse)

bca_2017 <- read_rds("Data/bca252.rds") %>% 
  filter(lubridate::year(sale_date) == 2017)
```

---

```{r}
aa_n <- bca_2017 %>% group_by(aa_label) %>% summarise(n=n())
```

```{r echo=FALSE}
aa_n %>% kable
```

---

```{r}
ggplot(aa_n) + geom_col(aes(aa_label, n))
```

---

```{r}
ggplot(bca_2017) + geom_bar(aes(aa_label))
```

---

.scroll-output[
.tiny[
```{r echo=FALSE}
bca_2017 %>% head(20) %>% kable
```
]]

---

.tiny[
```{r}
bca_2017_aa_act <- bca_2017 %>% group_by(aa_label, act_use_cat) %>% 
	summarise(n=n(), avg_price = mean(price, na.rm=TRUE))
```
]

.scroll-output[
.tiny[
```{r echo=FALSE}
bca_2017_aa_act %>% head(20) %>% kable
```
]]


---

.tiny[
```{r}
ggplot(bca_2017_aa_act) + geom_col(aes(aa_label, n, fill=act_use_cat), position = "stack")
```
]

---

```{r}
ggplot(bca_2017_aa_act) + 
  geom_col(aes(aa_label, n, fill=act_use_cat), position = "fill")
```

---

```{r}
ggplot(bca_2017_aa_act) + 
  geom_col(aes(aa_label, n, fill=act_use_cat), position = "dodge")
```

---

`geom_bar()` automatically calculates counts and use them as y. But `geom_col()` is more flexible. 

```{r}
ggplot(bca_2017_aa_act) + 
  geom_col(aes(aa_label, avg_price, fill=act_use_cat), position = "dodge")
```

---

Default value for `position=`

[? geom_col()](https://ggplot2.tidyverse.org/reference/geom_bar.html)
--

```{r}
ggplot(bca_2017_aa_act) + geom_col(aes(aa_label, n, fill=act_use_cat))
```

---

```{r}
ggplot(bca_2017_aa_act) + geom_col(aes(aa_label, n, fill=act_use_cat)) + coord_flip()
```

---

Practice task - Generate this figure, using `bca_2017_aa_act`.

```{r echo=FALSE}
ggplot(bca_2017_aa_act) + 
  geom_col(aes(act_use_cat, avg_price, fill=aa_label), position = "dodge")
```

--

.tiny[
```{r echo=params$answers, eval=FALSE}
ggplot(bca_2017_aa_act) + geom_col(aes(act_use_cat, avg_price, fill=aa_label), position = "dodge")
```
]

---

Practice task

```{r}
pumf_prihm <- read_rds("Data/2021_census_pumf_ind.rds") %>% 
  filter(PRIHM == "Person is primary maintainer", 
         AGEGRP != "Not available", 
         Tenur != "Not available")
```

Generate figures on next two slides. Try both `geom_col()` and `geom_bar()`.

---
 
```{r echo=FALSE}
ggplot(pumf_prihm) + geom_bar(aes(AGEGRP, fill=Tenur, weight=WEIGHT), position = "fill") + coord_flip()
```
--

.tiny[
```{r echo=params$answers, eval=FALSE}
ggplot(pumf_prihm) + 
  geom_bar(aes(AGEGRP, fill=Tenur, weight=WEIGHT), position = "fill") + 
  coord_flip()
```
]

---

```{r echo=FALSE}
ggplot(pumf_prihm) + geom_bar(aes(AGEGRP, fill=Tenur, weight=WEIGHT), position = "fill") + coord_flip() +
  scale_x_discrete(name=NULL) + 
  scale_y_continuous(name = NULL, labels= scales::label_number(scale=100, suffix = '%')) +
  scale_fill_discrete(name= NULL, labels= c("Own", "Rent"))
```
--
.tiny[
```{r echo=params$answers, eval=FALSE}
ggplot(pumf_prihm) + geom_bar(aes(AGEGRP, fill=Tenur, weight=WEIGHT), position = "fill") + coord_flip() +
  scale_x_discrete(name=NULL) + 
  scale_y_continuous(name = NULL, labels= scales::label_number(scale=100, suffix = '%')) +
  scale_fill_discrete(name= NULL, labels= c("Own", "Rent"))
```
]
